version: '3'

vars:
  RADR_CONFIG: ""

env:
  RADR_CONFIG: "{{ .RADR_CONFIG }}"

tasks:
  default:
    cmd: task --list

  build:
    desc: Build (debug)
    cmd: cargo build

  clean:
    desc: Clean build artifacts
    cmd: cargo clean

  release:
    desc: Build (release)
    cmd: cargo build --release

  fmt:
    desc: Format code with rustfmt
    cmd: cargo fmt --all

  clippy:
    desc: Lint with clippy (deny warnings)
    cmd: cargo clippy --all-targets --all-features -- -D warnings

  test:
    desc: Run unit tests
    cmd: cargo test --all

  run:
    desc: Run the CLI with arbitrary args
    vars:
      ARGS: "--help"
    cmd: cargo run -- {{ .ARGS }}

  # Convenience tasks for common commands
  cmd:new:
    desc: "Create a new ADR (var: TITLE)"
    vars:
      TITLE: "Example ADR"
    cmd: cargo run -- new "{{ .TITLE }}"

  cmd:supersede:
    desc: "Create an ADR superseding another (vars: ID, TITLE)"
    vars:
      ID: "1"
      TITLE: "Superseding ADR"
    cmd: cargo run -- supersede {{ .ID }} "{{ .TITLE }}"

  cmd:list:
    desc: List ADRs and regenerate index
    cmd: cargo run -- list

  cmd:index:
    desc: Regenerate index.md
    cmd: cargo run -- index
